//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TP_Web_Equipo_18_B
{
    public partial class ArticuloSeleccionado
    {
    }
}
